# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Number_Finder.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainPicture = QtWidgets.QLabel(self.centralwidget)
        self.mainPicture.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.mainPicture.setMouseTracking(False)
        self.mainPicture.setFrameShape(QtWidgets.QFrame.Box)
        self.mainPicture.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainPicture.setLineWidth(2)
        self.mainPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.mainPicture.setObjectName("mainPicture")
        self.takePictureButton = QtWidgets.QPushButton(self.centralwidget)
        self.takePictureButton.setGeometry(QtCore.QRect(290, 490, 75, 23))
        self.takePictureButton.setObjectName("takePictureButton")
        self.windowRaw = QtWidgets.QLabel(self.centralwidget)
        self.windowRaw.setGeometry(QtCore.QRect(651, 1, 261, 211))
        self.windowRaw.setFrameShape(QtWidgets.QFrame.Panel)
        self.windowRaw.setLineWidth(2)
        self.windowRaw.setAlignment(QtCore.Qt.AlignCenter)
        self.windowRaw.setObjectName("windowRaw")
        self.windowProcessed = QtWidgets.QLabel(self.centralwidget)
        self.windowProcessed.setGeometry(QtCore.QRect(650, 260, 261, 221))
        self.windowProcessed.setFrameShape(QtWidgets.QFrame.Panel)
        self.windowProcessed.setLineWidth(2)
        self.windowProcessed.setAlignment(QtCore.Qt.AlignCenter)
        self.windowProcessed.setObjectName("windowProcessed")
        self.updateWindowButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateWindowButton.setGeometry(QtCore.QRect(730, 230, 90, 23))
        self.updateWindowButton.setObjectName("updateWindowButton")
        self.classifyButton = QtWidgets.QPushButton(self.centralwidget)
        self.classifyButton.setGeometry(QtCore.QRect(740, 500, 90, 23))
        self.classifyButton.setObjectName("classifyButton")
        self.thresholdMult = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.thresholdMult.setGeometry(QtCore.QRect(650, 500, 62, 22))
        self.thresholdMult.setProperty("value", 1.6)
        self.thresholdMult.setObjectName("thresholdMult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainPicture.setText(_translate("MainWindow", "No picture yet"))
        self.takePictureButton.setText(_translate("MainWindow", "Take Picture"))
        self.windowRaw.setText(_translate("MainWindow", "Window Raw"))
        self.windowProcessed.setText(_translate("MainWindow", "Window Processed"))
        self.updateWindowButton.setText(_translate("MainWindow", "Process Window"))
        self.classifyButton.setText(_translate("MainWindow", "Classify!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
